


#서버포트 번호
server:
  port: 80

# 콘솔 ANSI 안시
spring:
  output:
    ansi:
     enabled: always

# thymeleaf ??
  thymeleaf:
   cache: false
   prefix: classpath:templates/views/


# datasource ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}


# security
  security:
    user:
      name: user1    #디폴트 security
      password: 1234   # password
    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 393867114881-qlvu0v1pmuepu9o7ashe4p4nlub3od4c.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


          facebook:
            client-id: 374777938237139 # 앱 ID
            client-secret: 74f582083c1dcb28bdfa9f2e91ef3f46 # 앱 시크릿 코드
            scope:
              - email
              - public_profile


          naver:
            client-id: m3I1qElDVt4qXRsxt_PR
            client-secret: PxbxSmyz1m
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        # provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response






# MyBatis ??(mapper) 파일 위치 설정
# src/main/resources ??? ?? ??
mybatis:
  mapper-locations: classpath:mapper/**/*.xml


app:
    # 파일 업로드 경로
    upload:
      path: upload

    # 페이징 관련 세팅값
    pagination:
      write_pages: 10  # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
      page_rows: 10   # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?


    # OAuth2
    oauth2:
      password: 1234

      #kakao 로그인 관련 세팅값
      kakao:
        client-id: 628606564702ae7ba9d6f249f9550b8a  #앱 키
        redirect-uri: http://localhost:8080/oauth2/kakao/callback #Redirect URI
        token-uri: https://kauth.kakao.com/oauth/token #access token 요청 URI
        user-info-uri: https://kapi.kakao.com/v2/user/me  #사용자 profile 요청URL








